management:
  endpoints:
    web:
      base-path: /psc-statement-data-api
      path-mapping:
        health: /healthcheck

chs:
  api:
    kafka:
      url: ${CHS_KAFKA_API_URL:localhost}
      uri: ${PSC_STATEMENTS_API_RESOURCE_CHANGED_URI:/private/resource-changed}
      kind: ${PSC_STATEMENTS_API_RESOURCE_KIND:persons-with-significant-control-statement}
    exemptions:
      url: ${COMPANY_EXEMPTIONS_API_LOCAL_URL:https://localhost}
      key: ${COMPANY_EXEMPTIONS_API_KEY:apiKey}
    metrics:
      url: ${COMPANY_METRICS_API_URL:https://localhost}
      key: ${COMPANY_METRICS_API_KEY:apiKey}

logger:
  namespace: psc-statement-data-api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://mongo:27017}/company_psc_statements?retryWrites=false
      name: company_psc_statements
  jackson:
    default-property-inclusion: NON_NULL

mongodb:
  pscStatements:
    collection:
      name: company_psc_statements
  transactional: ${TRANSACTIONAL_ON:false}
