management:
  endpoints:
    web:
      base-path: /company
      path-mapping:
        health: /healthcheck

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}
      enabled: ${DSQ_STREAM_HOOK_ENABLED:true}

logger:
  namespace: psc-statement-data-api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://mongo:27017}/company_psc_statements?retryWrites=false
      name: company_psc_statements
  jackson:
    default-property-inclusion: NON_NULL

mongodb:
  pscStatements:
    collection:
      name: company_psc_statements

company-metrics:
  api:
    url: ${COMPANY_METRICS_API_URL}

api:
  psc-statements-data-api-key: ${PSC_STATEMENTS_DATA_API_KEY:localhost}
  company-metrics-data-api-key: ${PSC_STATEMENTS_DATA_API_KEY:g9yZIA81Zo9J46Kzp3JPbfld6kOqxR47EAYqXbRV}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:http://api.chs.local:4001}