management.endpoints.access.default=read_only
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never

management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

api.key=${CHS_API_KEY:chsApiKey}
kafka.api.url=${CHS_KAFKA_API_URL:http://localhost:8888}
exemptions.api.url=${COMPANY_EXEMPTIONS_API_LOCAL_URL:https://localhost:8888}
metrics.api.url=${COMPANY_METRICS_API_URL:https://localhost:8888}

spring.mongodb.uri=${MONGODB_URL:mongodb://mongo:27017}/company_psc_statements?retryWrites=false
spring.data.mongodb.name=company_psc_statements
spring.jackson.default-property-inclusion=NON_NULL

mongodb.pscStatements.collection.name=company_psc_statements
mongodb.transactional=${TRANSACTIONAL_ON:false}

logger.namespace=psc-statement-data-api
server.port=${PORT:8081}
